name: EnchantmentAPI
main: com.rit.sucy.EnchantmentAPI
version: 3.1
commands:
    enchantapi:
        description: root command
        usage: /enchantapi show the help menu
    enchantapi list:
        description: lists all registered custom enchantments
        usage: /enchantapi
        permission: EnchantmentAPI.list
        permission-message: You lack the privileges to use that!
    enchantapi add:
        description: applies a custom enchantment
        usage: /enchantapi add <enchantName> [enchantLevel]
        permission: EnchantmentAPI.admin
        permission-message: You lack the privileges to use that!
    enchantapi reload:
        description: reloads the enchantments
        usage: /enchantapi reload
        permission: EnchantmentAPI.admin
        permission-message: You lack the privileges to use that!
permissions:
    EnchantmentAPI.list:
        description: basic list of enchantments
        default: true
    EnchantmentAPI.admin:
        description: applying enchantments
        default: op